// let marks = [91,82,63,84, false,"not present"];

// for(let i =0; i< marks.length;i++){
//     console.log(marks[i])
// }

//Array methods

// let num =[ 1,2,3,4,5,6];
// let num_more=[ 7,8,9,10,11,12,13,14,15,16];
// let b= num.toString();
// console.log("array b is "+b,typeof(b));

// let c = num.join("_");
// console.log(c);
// let r = num.pop();
// console.log(num, "poped element is "+r);
// let v= num.push(2);
// console.log(num, "Pushed element array length  "+ v);

// let a= num.shift();
// // console.log(a, num);
// let b= num.unshift(1);
// console.log(b);

// delete num[0];
// console.log(num);

// let new_array = num.concat(num_more);

// console.log(new_array);

//  let num =[ 13,2,34,4,5,6,10,12,13,14,18,19];
//  num.sort();  // sort the array alphabetically
//  console.log(num)

// let compare1 = (a, b)=>{
//     return a-b ;
// }
// num.sort(compare1);
// console.log(num);
// num.reverse();
// console.log(num);
// let deletedValues=num.splice(2,4,220,223,444);
// console.log(num);
// console.log(deletedValues);
// let new_array = num.slice(2);
// let new_array = num.slice(3,6);
// console.log(new_array);

//Loopings with Arrays
// let new_num = [1,2,3,4,5,6,7,7,8,9];
// FOR
// for (let i =0 ;i<new_num.length; i++){
//     console.log(new_num[i])
// }
// FOR IN
//  for(let i in new_num);
//  {
//     console.log(new_num[i]);
//  }

// FOr of
// for(let i of new_num){
//     console.log(i);
// }

// FOR EACH
// new_num.forEach((element) => {
//     console.log(element*element)

// });

// Array.from
// let name1 ="Akanksha";
// let arr = Array.from(name1);
// console.log(arr);
// arr.forEach((elemnts)=>{
// console.log(elemnts)
// });

// Map filter reduce function
// let arr =[1,5,7,8,9,0,2,5];

// console.log(arr);
//map return new arrays

// let a = arr.map((i)=>{
//  console.log(i);
//  return i+1;
// });
// console.log(a);

// let a = arr.map((value, index, array)=>{
// console.log(value, index, array);
// });

//array filter method  it does not change the original array
// let arr2 = [4,7,8,9,10,12,13,14,15,16];

// let a= arr2.filter((i)=>{
// return i>10;
// });
// console.log(a);

//reduce array methhod

// let arr3 = arr2.reduce((h1,h2)=>{
//     return h1 +h2;
// });
// console.log(arr3);

// create an array of numbers an d take input
// from the users to add numbers top this array
// let arr =[1,2,3,4];
// let user_input = prompt("enter the number");
// user_input =Number.parseInt(user_input)
// arr.push (user_input);
// console.log(arr);

// keep adding numbers to the above arrau until 0 is added to the array

//  let arr =[1,2,3,4];
//  let user_input
//  do {
//      user_input = prompt("enter the number");
//     user_input = Number.parseInt(user_input);
//     arr.push(user_input);

//  }while(user_input !=0)
//     console.log(arr);

// filters for numbers divisilbe by 10 from a given array
//   let arr =[1,20,30,4,50];
//  let new_arr= arr.filter( (x)=>{
//     return x%10===0;
//  });
//  console.log(new_arr);

// create an array of square of given number
//   let arr =[1,20,30,4,50];
//   let new_arr = arr.map((x)=>{
//      return( x*x);
//   });
//   console.log(new_arr)

// use reduce to calculate factorial of a given number from an array of first n natural numbers

// let arr =[1,2,3,4,5];
// let new_arr = arr.reduce((x1,x2)=>{
// return (x1 *x2)
// })
// console.log(new_arr);

// array exercise 1
//write a javascript program to generate a random number and store it in a
// variable the program thne takes an input from the usesr to then
// whether the guess was correct , greated or lesser than the original number
//100 -  (no of guesses) is the score of the user
// The program is expected to terminate once the number
// is gussed number should be b/w 1 to 100

let num = Math.floor(Math.random() * 100 + 1); // Generates a random number b/w 1 and 100
console.log(num)
let chances = 0;
console.log(`This is a guessing game and you
         have to enter a number and if it matches with 
        the number generated by computer, then you win...\n`);
let user_input = prompt("Enter a number b/w 1 to 100");
++chances;
do {
user_input = Number.parseInt(user_input);
if (user_input > num) {
    console.log("Your input is greater");
    user_input = prompt("Enter again");
    user_input = Number.parseInt(user_input);
    ++chances;
    continue;
}
else if (user_input < num){
console.log("Number entered is smaller");
    guess = prompt("Enter again!!");
    guess = Number.parseInt(guess);
    ++chances; //To increment the number of chances taken
    continue;
}
}while(user_input !=num)
    let score = 100 - chances; //To store the score of your game
console.log("\nCongratulations🥳🥳\nThe number generated was", number + " and you guessed it right😁\nYour final score is", score);